- name: ansible-tooa12
  hosts: tooa12
  gather_facts: true
  tasks:
      - name: Print all available facts
        ansible.builtin.debug:
            var: ansible_hostname
      # - name: Print install sonarqube
      #   shell: |
      #       sudo apt update -y
      #       sudo apt install docker.io -y
      #       sudo docker run -d --name sonarqube -p 9000:9000 sonarqube
      - name: Instsall java
        shell: sudo apt install openjdk-17-jre
      - name: Check java version
        shell: java -version
        register: java_version
      - name: Set fact java version
        set_fact: version_java = "{{ java_version.stdout }}"
      - name: Print java version
        ansible.builtin.debug:
            var: version_java
