- name: ansible-tooa12
  hosts: tooa12
  gather_facts: true
  tasks:
      - name: Print all available facts
        ansible.builtin.debug:
            var: ansible_hostname
      - name: Print install sonarqube
      shell: |
          sudo apt update -y
          sudo apt install docker.io -y
          sudo docker run -d --name sonarqube -p 9000:9000 sonarqube
